sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: jyRxjeGzB0UApOv+C8COEf2skGCtCUciAJKzTT7ftowLvUIrlKflY4i+Au0GpfmrJ0klmW4VRjBYyrjOsezwv6LuJnXme7p4G57hscNjL4hmVs4MjNxSA6gIuu1eDedLPaxBsb+2qrzjrZ2axWbPX+p0hib+VYsfBJ/J+mVqIzaBlz0Ti0MvxG6zkRw9MfU7mKwq3stV2OZnR6eNAO65G9EXYuMqm7MKzRcF1orHbyx0zj/4NOPmeY6OHmpYuuvkd98qjSS6mvzyr7b4S0reY2gHjYF2My5asKsShPInhoYaiadsuaK4l3VVUuZ09Dw/ekZkC/renRjT9sVsBqS3JqYjTj63pKpwS3eK5JzBu5R6igqwDI7RMWASDv2ICe4E5iQUMzyyJEegd7zQi0K/37+DmEnFfDJfY6BioPxf66B9/sIy59S/Gf23YNEVcpN4Sd3VduMCtsmPKRmRTvHimrs18id3tpEVeTOWPKG+pUmF6Uhkgu/lLVy+mocu+E5/7vd4v+9l930+a3Iqq+NOCDoevpS69Jl3R2fsy3mBjK0F4MUJmczPGZsF/j1iYCU6qnut4w06vdytjzRICVchxQaL7fi25+yvCm7Z2Aq/XtkGpcT2lnyHNPRDHX2XE1J7NrZigMsikheo/296bknj9MNytoZR5hk0iLhS4nZxzkE=
  - secure: UOutRmJLfvMSZcK7EylDnT3QwTfee6MD6OX/7YqIQZsvphHl65SMBcuSRDIjW2srosHHQRpcsR+HPc1PJWII8Jpy8KJ7wcPIP/ntWqcN8bvJd8hprtdaMWfBa8OSj/ZJF7vUqj29ub2QdvFImb2q0CqjGb3C7ZnO4ezdnMlMEF2SFJMINBYE7Lry7fk0cIYEnsgKGz+p9KavNBNHxMmqN7dTQqfJzc/VkcK0azyzZw0vlPCVx/dRdu1C9/mfIIB96QeyPM9FOAVyYKgskaN7mlJWxGYqOdgqaZ4mfd1faUGV7s/Br7grqp09LOkO1hy/5ktz4TH40dcJhTvvW251mCWxo4LmHObyYOIzkXZj/SjDdtmif5Ab4jYFertp4/TPq9ICUjF6cCaRMHcFXuMLRJHNkCoxydHmSRZ56GzHKMroy/wQuTvTi6mBK6XZO/xdZnRzisdkmiZGs4u0ERAZ1Vv/K3i4jU+7oHCgIGTP5IhaT507E1kfEFmu6S8AoAq1iId1s31qcQNxpLN5Vlq5tqxUNyRbPpPZohQt1dbkQ3LEIi1SLFVf5pCpqQe3zl0iG2VXKmuywglQALDsj15BPXANion45163PIozpnWYlBwqrm6VqXsmQgl5wrmHu/OK3cLaWLcYrKvtCCZtOgDBPpExheWstTRfwifNbU7gToE=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: tkniMqgy0eeQ7CNmO+AU8XXWDSnYnIWED/VBxsCrH9eFq/4X2dl0tiGHGg8h18r8dF5udo0FyQudZ0iK+VEihmjhZaQy3OL22luh5Obq4pwE2yNBl6XEBt0W8+sAP+AxQhlu7xFtrqh6htwX7kDRFHCvaj1azxiD3h1qEPksMImLX7GLkzrnpZiKDNGhPnatRb71HYsgpy+whuQ3eju6I4hvPYXNWhFfN0/oJfPJBNvcdwGW5/8e1yxvlHWxBotdD0rfpY1W4vNsE5fyJj9BHyGiloBz2qJjtRqt/1o40yta+nycrgCXJxewuD+5w60U1J2lolkauo+tpNshPQtbdDKWTe4SKKiuZe1cq1sWO5Afi8h0Y6SjJ1PrJt2NquX8d7SCQj4DdTY1uYvp5SitFl2JuOSHDuVINCgLJHmMQHygxOStCSU6MbJepznvM2VBmKbypWwwCBRE0t4usL3iu98FXHsJOw/dyMqKYOYhVW/51fnYKj4L1mampJRjtu54QxLo1domHEAp9oN3AhmLQVlOTPwyy80PCnhw8j5D85SG0HcZfLmWsaxhM1ke3n0G7V11yjKqlc1FByAZ7YCX0wtbzBjGvA7KSGB3Xdj4yzuEgP4QFTNIv2JjvtUEi7DPqw1aFYQqw8tAGGnM3FbR7DZ/ysbKAQ33UM4PO94o/GQ=
