name: Generate docs
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: ls1
        run: |
          pwd
          ls -la
          git remote -v

      - name: Clone wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki

      - name: ls2
        run: |
          pwd
          ls -la
          ls -la .wiki
          git remote -v

      - name: look inside container
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/sh
          args: -c "ls -la ; ls -la .wiki ; pwd"

      - name: Parse and generate docs
        uses: p3lim/lua-doc-parser@master
        with:
          path: .wiki

      - name: ls3
        run: |
          pwd
          ls -la
          ls -la .wiki

      - name: diff
        run: |
          cd .wiki
          git config user.name CI
          git config user.email "<>"
          git status
          git diff
