name: Generate docs
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Clone wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
      - name: Parse and generate docs
        uses: p3lim/lua-doc-parser@master
        with:
          path: ${{ github.repository }}.wiki
      - name: Commit and push changes
        run: |
          pwd
          ls -la
